spring:
  application:
    name: itachallenge-gateway
  config:
    import: optional:consul:localhost:8500

server:
    port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false

logging:
  level:
    root: INFO
    "[org.springframework.cloud.gateway]": DEBUG
  pattern:
    # console: Spring's default
    file: "%date %5level %-40.40logger{39} [%thread] %msg%n"
#  file:
#    name: itachallenge-challenge.log
