spring:
  application:
    name: itachallenge-user
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  jmx:
    enabled: true
  data:
    mongodb:
      uri: mongodb://admin_user:yxRG4sYBDjPFzbh5@localhost:27017/users?authSource=admin
      uuid-representation: standard

redis:
  port: 6379
  host: 127.0.0.1
  password: PwSxkcnmaqUQN3FvESjh1eD0UEGx5shz
  user:
    key: USER


springdoc:
  swagger-ui:
    path: "/swagger-ui-custom.html"
    operationsSorted: method
  api-docs:
    enable: true
    path: "/api-docs"

server:
  port: 8764

management:
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false

url:
  max_length: 2048

logging:
  level:
    root: INFO
    "[org.springframework]": ERROR
    "[com.businessassistantbcn]": INFO
  pattern:
  # console: Spring's default
    file: "%date %5level %-40.40logger{39} [%thread] %msg%n"
#  file:
#    name: itachallenge-user.log

validation:
  mongodb_pattern: "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
