spring:
  application:
    name: itachallenge-user
  jmx:
    enabled: true

redis:
  port: 6379
  host: 127.0.0.1
  password: PwSxkcnmaqUQN3FvESjh1eD0UEGx5shz
  user:
    key: USER


springdoc:
  swagger-ui:
    path: "/swagger-ui-custom.html"
    operationsSorted: method
  api-docs:
    enable: true
    path: "/api-docs"

server:
  port: 8764

management:
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false

url:
  max_length: 2048

logging:
  level:
    root: INFO
    "[org.springframework]": ERROR
    "[com.businessassistantbcn]": INFO
  pattern:
  # console: Spring's default
    file: "%date %5level %-40.40logger{39} [%thread] %msg%n"
#  file:
#    name: itachallenge-user.log

