plugins {
    id 'java'
    id 'org.springframework.boot' version '3.0.6'
    id 'jacoco'
}
bootJar {
    enabled = false
}
jar {
    enabled = true
}

group = 'com.itachallenge'
version = '1.0.0'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter:3.0.6'
    implementation 'io.jsonwebtoken:jjwt-api:0.12.6'
    implementation 'io.jsonwebtoken:jjwt-impl:0.12.6'
    implementation 'io.jsonwebtoken:jjwt-jackson:0.12.6'
    implementation 'org.slf4j:slf4j-api:1.7.32'
    implementation 'org.projectlombok:lombok:1.18.30'
    annotationProcessor 'org.projectlombok:lombok:1.18.30'

    testImplementation group: 'com.squareup.okhttp3', name: 'mockwebserver', version: '4.12.0'
    testImplementation 'org.springframework.boot:spring-boot-starter-test:3.0.6'
    testImplementation 'org.springframework:spring-test:5.3.13'
    testImplementation 'org.mockito:mockito-core:5.3.1'
    testImplementation 'org.hamcrest:hamcrest:2.2'
    testImplementation 'io.projectreactor:reactor-test:3.1.0.RELEASE'
    testImplementation 'org.testcontainers:junit-jupiter:1.17.6'
    testImplementation 'org.junit.platform:junit-platform-suite-engine:1.8.1'
}

test {
    jvmArgs "-Xshare:off"
    useJUnitPlatform()
    finalizedBy jacocoTestReport
}

jacocoTestReport {
    dependsOn test
    reports {
        xml.required = true
        csv.required = false
        html.outputLocation = layout.buildDirectory.dir('jacocoHtml')
    }
}

// JaCoCo configuration: https://docs.gradle.org/current/userguide/jacoco_plugin.html
jacocoTestCoverageVerification {
    violationRules {
        rule {
            limit {
                counter = 'LINE'
                value = 'COVEREDRATIO'
                minimum = 0.7
            }
        }
    }
}

sonar {
    properties {
        property "sonar.coverage.jacoco.xmlReportPaths", layout.buildDirectory.file("reports/jacoco/test/jacocoTestReport.xml").get().asFile.absolutePath
    }
}