spring:
  application:
    name: itachallenge-auth
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  jmx:
    enabled: true

springdoc:
  swagger-ui:
    path: "/swagger-ui-custom.html"
    operationsSorted: method
  api-docs:
    enable: true
    path: "/api-docs"

server:
  port: 8761

management:
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false

uri_validate_token : https://dev.sso.itawiki.eurecatacademy.org/api/v1/tokens/validate


logging:
  level:
    root: INFO
    "[org.springframework]": ERROR
    "[com.businessassistantbcn]": INFO
  pattern:
    # console: Spring's default
    file: "%date %5level %-40.40logger{39} [%thread] %msg%n"
#  file:
#    name: itachallenge-challenge.log

