spring:
  application:
    name: itachallenge-auth
    version: 2.0.0-RELEASE
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  jmx:
    enabled: true
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: login

springdoc:
  swagger-ui:
    path: "/swagger-ui-custom.html"
    operationsSorted: method
  api-docs:
    enable: true
    path: "/api-docs"

server:
  port: 8761

management:
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false

uri_validate_token : https://dev.sso.itawiki.eurecatacademy.org/api/v1/tokens/validate

user:
  service:
    url: http://172.17.0.2:8764 # LOCAL IP
    # SHOULD BE http://apisix-gateway:9080 IN PRODUCTION

logging:
  level:
    root: INFO
    "[org.springframework]": ERROR
    "[com.businessassistantbcn]": INFO
  pattern:
    # console: Spring's default
    file: "%date %5level %-40.40logger{39} [%thread] %msg%n"
#  file:
#    name: itachallenge-challenge.log

