spring:
  application:
    name: itachallenge-challenge
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  jmx:
    enabled: true

springdoc:
  swagger-ui:
    path: "/swagger"
    operationsSorted: method
  api-docs:
    enable: true
    path: "/api-docs"

server:
  port: 8764

management:
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false

logging:
  level:
    root: INFO
    "[org.springframework]": ERROR
    "[com.businessassistantbcn]": INFO
  pattern:
    # console: Spring's default
    file: "%date %5level %-40.40logger{39} [%thread] %msg%n"
#  file:
#    name: itachallenge-challenge.log

url:
  connection_timeout: 30000
  maxBytesInMemory: 30000000

