spring:
  application:
    name: itachallenge-document
    version: 2.0.0-RELEASE

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  jmx:
    enabled: true


redirect-api:
  auth:
    url: "http://localhost:8761"
  challenge:
    url: "http://localhost:8762"
  score:
    url: "http://localhost:8763"
  user:
    url: "http://localhost:8764"


springdoc:
  swagger-ui:
    path: "/swagger"
    urls:
      - name: Auth OpenAPI Definition
        url: "/api-docs/auth"
      - name: Challenge OpenAPI Definition
        url: "/api-docs/challenge"
      - name: User OpenAPI Definition
        url: "/api-docs/user"
      - name: Score OpenAPI Definition
        url: "/api-docs/score"
      - name: All OpenAPI Definition
        url: "/api-docs" # or /api-docs/all  (redirect link)
    show-request-headers: true
    show-extensions: true
    disable-swagger-default-url: true
  api-docs:
    enable: true
    path: "/api-docs"
  cache:
    disabled: true

server:
  port: 8769

management:
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false

logging:
  level:
    root: INFO
    "[org.springframework]": ERROR
    "[com.businessassistantbcn]": INFO
  pattern:
    # console: Spring's default
    file: "%date %5level %-40.40logger{39} [%thread] %msg%n"
#  file:
#    name: itachallenge-challenge.log

url:
  connection_timeout: 30000
  maxBytesInMemory: 30000000


