plugins {
    id 'java-library'
}

group = 'com.barrisense.common'
version = '1.0.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
    withJavadocJar()
    withSourcesJar()
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web:3.3.3'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.0'
}

tasks.test {
    useJUnitPlatform()
}
