plugins {
    id 'java'
    id 'org.springframework.boot' version '3.0.6'
    id 'jacoco'
}

jar {
    manifest {
        attributes(
                'Main-Class': 'com.itachallenge.user.App'
        )
    }
}

jacoco {
    toolVersion = '0.8.11'
    reportsDirectory = layout.buildDirectory.dir('jacocoXml')
}

group = 'ita.challenges'
version = System.getenv('MICROSERVICE_VERSION') ?: '1.0.1-RELEASE'

repositories {
    mavenCentral()
}

dependencies {

    implementation 'org.springframework.boot:spring-boot-autoconfigure:3.0.6'
    implementation 'org.springframework.cloud:spring-cloud-commons:4.0.1'

    implementation 'org.springframework.boot:spring-boot-starter-web:3.0.6'
    implementation 'org.springframework.boot:spring-boot-starter-webflux:3.0.6'

    implementation 'org.springframework.boot:spring-boot-starter-data-mongodb:3.0.6'
    implementation 'org.springframework.boot:spring-boot-starter-data-mongodb-reactive:3.0.6'

    implementation 'org.springframework.boot:spring-boot-starter-actuator:3.0.6'

    implementation 'org.projectlombok:lombok:1.18.30'
    annotationProcessor 'org.projectlombok:lombok:1.18.30'

    implementation 'org.apache.commons:commons-lang3:3.12.0'

    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.1.0'

    implementation 'org.springframework.cloud:spring-cloud-starter-consul-config:4.0.2'
    implementation 'org.springframework.cloud:spring-cloud-starter-consul-discovery:4.0.2'
    implementation 'org.springframework.cloud:spring-cloud-starter-bootstrap:4.0.2'

    implementation 'org.springframework.boot:spring-boot-starter-data-redis-reactive:3.1.1'

    implementation project(":github-core")

    // TESTING

    testImplementation platform("org.testcontainers:testcontainers-bom:1.20.4")

    testImplementation "org.testcontainers:testcontainers"
    testImplementation "org.testcontainers:junit-jupiter"
    testImplementation "org.testcontainers:mongodb"

    testImplementation 'org.springframework.boot:spring-boot-starter-test:3.0.6'

    testImplementation 'org.mockito:mockito-core:5.3.1'
    testImplementation 'org.assertj:assertj-core:3.24.2'
    testImplementation 'org.hamcrest:hamcrest:2.2'

    testImplementation 'io.projectreactor:reactor-test:3.1.0.RELEASE'

}

test {

    useJUnitPlatform()

    testLogging {
        events "PASSED", "FAILED", "SKIPPED"
        exceptionFormat "FULL"
    }

    jvmArgs "-Xshare:off"

    finalizedBy jacocoTestReport
}

jacocoTestReport {

    dependsOn test

    reports {

        xml.required = true
        csv.required = false
        html.outputLocation = layout.buildDirectory.dir('jacocoHtml')
    }
}

sonar {

    properties {

        property "sonar.projectKey", "IT-Academy-BCN_ita-challenges"
        property "sonar.organization", "it-academy-bcn"

        property "sonar.coverage.jacoco.xmlReportPaths",
                "${layout.buildDirectory.get()}/jacocoXml/test/jacocoTestReport.xml"
    }
}
