name: Pull Request Sonar Analysis

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [develop]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    env:
      DOCKER_HOST: unix:///var/run/docker.sock
      TESTCONTAINERS_HOST_OVERRIDE: localhost
      TESTCONTAINERS_RYUK_DISABLED: true

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Verify Docker
        run: |
          docker version
          docker info

      - name: Run Tests
        id: run_tests
        continue-on-error: true
        run: ./gradlew test --console=plain --info --stacktrace

      - name: List failed tests
        if: always()
        run: |
          echo "FAILED TESTS:"
          find . -name "*.xml" -path "*/test-results/*" -exec grep -H "<failure" {} \; || true

      - name: Fail job if tests failed
        if: steps.run_tests.outcome == 'failure'
        run: exit 1

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: "**/build/test-results/test/"

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: "**/build/reports/tests/"

      - name: SonarCloud Analysis
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonar --info
