name: Build
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Execute SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_URL }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            ./deploy_dev.sh


